version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - APP_SETTINGS=config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@database-dev:5432/forum_dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  database:
    container_name: database-dev
    build:
      context: ./backend/app/db/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    
